# Generated by Django 2.2.24 on 2021-06-06 09:57

from django.db import migrations, models
import djongo.models.fields
import djongo_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('slug', models.TextField(db_index=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', djongo.models.fields.EmbeddedField(model_container=djongo_app.models.Article, null=True)),
                ('meta_data', djongo.models.fields.EmbeddedField(model_container=djongo_app.models.MetaData, null=True)),
                ('headline', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('n_comments', models.IntegerField()),
                ('authors', models.ManyToManyField(to='djongo_app.Author')),
            ],
        ),
    ]
